# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [1]:
# import libraries and dataset
import pandas as pd 
import numpy as np

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv'
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
df.head(2)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [8]:
# Create a new Dataframe based on 2 conditions low total_claim_amount (e.g., below $1,000) response "Yes" to the last marketing campaign
filtered_df = df[(df['Total Claim Amount'] < 1000) & (df['Response'] == "Yes")]
# ne pas oublier df et squared brackets!
filtered_df

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

In [10]:
# filter + pibot table (il suffit de mettre le filtre en amont (en gros le fitlre entre square brackets et le nom du df avant
# pivot_df = df[df["Response"] == "Yes"].pivot_table(index='Gender', columns='Policy Type', values=['Monthly Premium Auto', 'Total Claim Amount'], aggfunc='mean')
# pivot_df = round(pivot_df,0)
# print(pivot_df)

            Monthly Premium Auto                             \
Policy Type       Corporate Auto Personal Auto Special Auto
Gender
F                           94.0          99.0         92.0
M                           92.0          91.0         86.0

            Total Claim Amount
Policy Type     Corporate Auto Personal Auto Special Auto
Gender
F                        434.0         453.0        453.0
M                        409.0         457.0        430.0

# IRON HACK AI Solutions

pivot_df = df[df["Response"] == "Yes"].pivot_table(index='Gender', columns='Policy Type', values=['Monthly Premium Auto', 'Total Claim Amount'], aggfunc='mean')
print(pivot_df)

# full DataFrame group by
result = df.groupby(['Policy Type', 'Gender']).agg({"Monthly Premium Auto":['mean'], "Total Claim Amount": ['mean']}

Among customers who answered “Yes,” women pay slightly higher monthly premiums than men on average for all types of policies. Claim amounts are broadly similar, but slightly higher for women in Corporate and Special Auto, and slightly higher for men in Personal Auto. There is relatively little difference between monthly premiums and claim amounts (approximately 15 dollars difference between minimum and maximum premiums, and less than 50 dollars for claim amounts). The Special Auto segment for men appears to be more profitable or less risky, while Personal Auto appears to be riskier due to higher claim amounts. These two variables do not appear to be sufficient for analyzing the data.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [5]:
# 2. analyze monthly premium auto and total claim amount through gender and policy type (all df)
df.groupby(['Policy Type', 'Gender']).agg({"Monthly Premium Auto":['mean'], "Total Claim Amount": ['mean']} )

                      Monthly Premium Auto Total Claim Amount
                                      mean               mean
Policy Type    Gender
Corporate Auto F                 91.384615         397.799287
               M                 94.764249         462.223565
Personal Auto  F                 93.153179         413.239658
               M                 93.301056         459.919476
Special Auto   F                 93.563025         458.139623
               M                 93.197044         420.355202

Corporate Auto female customers provide correct premiums while having the lowest claims, making them the most profitable and least risky segment.
In contrast, men in the Corporate Auto and Personal Auto segments have much higher claims despite similar or higher premiums, which reduces their profitability.
The other segments (Special Auto) are somewhere in between, but remain less optimal than Corporate Auto of Female.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [50]:
df.groupby("State")["Customer"].count()

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

In [52]:
grouped = df.groupby('State')
df_group = grouped.size() 
df3 = pd.DataFrame(df_group)
display(df3)

               0
State
Arizona     1937
California  3552
Nevada       993
Oregon      2909
Washington   888

All states have more than 500 customers, therefore there was no need of filtering data. California has the highest number, and Nevada the lowest. We can observe a division among countries, with Nevada and Washington having the less customers, then Arizona in the middle.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [55]:
df4 = round(df.groupby(['Education', 'Gender']).agg({"Customer Lifetime Value":['max','min','median']} ),2)
df4

                            Customer Lifetime Value
                                                max      min   median
Education            Gender
Bachelor             F                     73225.96  1904.00  5640.51
                     M                     67907.27  1898.01  5548.03
College              F                     61850.19  1898.68  5623.61
                     M                     61134.68  1918.12  6005.85
Doctor               F                     44856.11  2395.57  5332.46
                     M                     32677.34  2267.60  5577.67
High School or Below F                     55277.45  2144.92  6039.55
                     M                     83325.38  1940.98  6286.73
Master               F                     51016.07  2417.78  5729.86
                     M                     50568.26  2272.31  5579.10

Customer Lifetime Value does not vary drastically by education level, 
as median values remain relatively similar across groups. 
However, males with a “High School or Below” education level show the highest median and maximum CLV."

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9